dist: trusty
sudo: require
os: linux
language:
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cmake
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - export CC=gcc-7
  - cd ./C-DataStructures-Library
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make
  - ./C_DataStructures_Library_Tests
  - travis_wait 60 ./C_DataStructures_Library_Benchmarks
after_success:
  - bash <(curl -s https://codecov.io/bash)