dist: trusty
sudo: require
language:
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
script:
  - cd ./C-DataStructures-Library
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./C_DataStructures_Library
